### PR TITLE
update jupyterbook

### PR DESCRIPTION
**Pull request by jeremyforest**
Improvements of documentation. Review notebook tutorials with #32 in mind. Improvements toward #27  and #20

### CODE REVIEW

**Comment by jeremyforest** [comment]
@healthonrails  you should be able to view the jupyterbook localy by opening book/_build/html/index.html in your browser if you pull the PR on your local machine.

**Comment by healthonrails** [comment]
F821 undefined name 'get_ipython'
./book/_build/jupyter_execute/tutorials/Annolid_on_Detectron2_Tutorial_Example_Dataset.py:336:1: F821 undefined name 'get_ipython'
get_ipython().run_line_magic('tensorboard', '--logdir output')
Could you please import get_ipython in the Annolid_on_Detectron2_Tutorial_Example_Dataset.py file?

**Comment by jeremyforest** [comment]
ah that was a temp file I made and then spliced it into the different subsections. Let me clean that up.

**Comment by jeremyforest** [comment]
I actually forgot to delete the file from the folder but deleted it from the book. Done now, so the issue should be gone. Let me know if there are others.

**Pull request merged**
